### ISSUE TITLE
Share functionality

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#170]
For ensuring the share buttons function correctly across all site landings, here's a structured approach:

1. **Verification of Current Functionality**: 
   - Start by auditing each landing page to ensure that share buttons are present and properly initiating share operations. 
   - This includes checking for any console errors or network issues when the share button is clicked.

2. **Conditional Logic for Logged-in Users**:
   - Implement a mechanism to check the user's login status when the share button is clicked.
   - If the user is logged in, append `referrer=account.bk` as a query parameter in the URL used when making the request to the URL shortening service (dub).

3. **Integration with URL Shortening Service**:
   - Confirm that the service (dub) accepts and processes the modified URL correctly.
   - Handle any API response errors gracefully, providing feedback to the user if the shortlink cannot be generated.
   
 4. **Read referrer  when generating qr code for esr login**:
    - Add referrer to esr qr
    - Make sure referrer is read on bitcash app

**Comment by AndlerRL** [comment]
@gaboesquivel -- For the 4th point, is there any reason to add the referrer to the Bitcash Signature Request? I am trying to understand the reasoning behind: what should we be doing with the referrer on a signature if this referrer can be either the same account or the referrer?

**Comment by gaboesquivel** [comment]
@gaboesquivel If share  bitlancher.ai?referrer=gaboesquivel    my account needs to be saved on the bitcash db when the user create a new bitcash account from qr code.

**Comment by AndlerRL** [comment]
Oh I see! @TopETH , this is then the QR code and redirect for someone that has been referred. So, getting it on steps, it is:

1. User click "Share" on the project page. We generate a hash with the user account (if logged) as referrer.
  a. It is important to provide the `website` (`source` in our database) as `bitlauncher.ai`. It is very important to know if this referral came from another site hence, we can provide the right marketing & community to them. 
2. Another user clicks to the shared link made by the first user.  Opens it up, takes the user to bitlauncher and if they want to register, this `referrer` and `source` is now on part of the QR/redirection.
3. The new user completes the KYC with the first user account as referrer and the source is `bitlauncher.ai`.

**Comment by gaboesquivel** [comment]
@TopETH @AndlerRL yes exactly!, but it's not on the ESR QR code it's on GET BITCASH APP QR code, the qr to register

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Development Support, Nathan - May 2024](https://trello.com/c/BWeEuUCM/28-development-support-nathan-may-2024)
