### ISSUE TITLE
Test wallet connect integration

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#183]
Test wallet connect integration on dev.bitlauncher.ai both on desktop and mobile

**Comment by Bran18** [comment]
Hi everyone,

I'm handling this issue as requested by @TopETH 

@gaboesquivel , could you provide any recommendations, further descriptions, or important considerations for testing on this issue in dev.bitlauncher.ai?

CC. @AndlerRL

**Comment by AndlerRL** [comment]
Hey @Bran18 , checkout the issue #48 , it is related with this one and I made a recording of the flow but on production. It should be the same experience as on dev.bitlauncher.ai

**Comment by Bran18** [comment]
Hey guys @AndlerRL , @gaboesquivel  and @TopETH, Im adding a link to my bitcash drive account, github is showing the following: "File size too big: 25 MB are allowed, 49 MB were attempted to upload". 

Test Videos: https://drive.google.com/drive/folders/1-XnSFVueLybtdRcYMPI9QN-cSXAsNgdh?usp=sharing

Test are from:

- Mobile iPhone 12 - Public wifi
- Macbook air m1 - Public wifi

Wifi details: 

- IP: 191.102.58.43
- Upload: 50Mbps
- Download: 60Mbps

**Comment by gaboesquivel** [comment]
closed by #2e2ca5d
