### ISSUE TITLE
Fix newsletter registration

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#186]
![image](https://github.com/bitcashorg/smartsale/assets/391270/2eaf651a-f275-4d78-ab0c-e8bb7191d6a3)

To address the issues with the registration letter, follow these steps:

1. **Ensure Subscriptions Work:**
   - Verify the backend logic that handles subscriptions. Ensure that when a user registers, their email is correctly processed and stored.
   - Check the integration with your email service provider to confirm that emails are added to the resend collection as expected.

2. **Confirmation Message:**
   - Implement or verify the front-end code to display a confirmation message upon successful registration. This should be clear and inform the user that their registration is successful or pending confirmation.

3. **Error Management:**
   - Implement logic to clear any displayed errors when the user updates the input fields. This typically involves resetting the error state in response to input field changes.

**Comment by AndlerRL** [comment]
## High level test:

For me worked, I was able to subscribe with a tag:

![image](https://github.com/bitcashorg/smartsale/assets/35474730/aa416e42-ccd6-4c83-ad12-1ea057379736)

Also without a tag:

![image](https://github.com/bitcashorg/smartsale/assets/35474730/0dc47647-e653-4d15-84e5-95d7ca34d128)

Which team on resend do we have the registered contact list?

> NOTE: I think the "Unexpected error" message comes from recaptcha -> https://vercel.com/bitcash/bitlauncher/logs?page=2&timeline=maximum&startDate=1715213412750&endDate=1715299812750&selectedLogId=1715259615131961513122300000&selectedLogTimestamp=1715259615131&forceEndDate=1715294002984

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Development Support, Nathan - May 2024](https://trello.com/c/BWeEuUCM/28-development-support-nathan-may-2024)
