### ISSUE TITLE
Fix register button text on mobile

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#188]
![image](https://github.com/bitcashorg/smartsale/assets/391270/1c7e81d4-44c1-4d8a-a4c7-9e8d95b3564a)

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Development Support, Nathan - May 2024](https://trello.com/c/BWeEuUCM/28-development-support-nathan-may-2024)
