### ISSUE TITLE
change z-index recaptcha logo below other elements

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#193]
![image](https://github.com/bitcashorg/smartsale/assets/391270/f7466173-ed88-420e-9a30-e4a65bed75d4)

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Development Support, Nathan - May 2024](https://trello.com/c/BWeEuUCM/28-development-support-nathan-may-2024)
