### ISSUE TITLE
OG images

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#199]
Update global og image with this one https://www.figma.com/design/xKWICiVwIbEG75cad5nr3o/bitlauncher-Landing?node-id=387-108&t=Q82qXEhbefjwfkcm-4

For project landing page use project image as background and display title and pitch dynamically in the middle, copy code from masterbots search https://github.com/bitcashorg/masterbots/blob/search/apps/masterbots.ai/app/og/route.tsx

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Bitlauncher] Set And Update OG Images](https://trello.com/c/t7x9Xcqm/35-bitlauncher-set-and-update-og-images)
