### ISSUE TITLE
Include app name in esr info object

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#28]
Include appName in all esr requests, inside the info object

![Image](https://github.com/bitcashorg/smartsale-evm/assets/391270/8b7afd25-45f9-4f8f-80d2-ab230f24c189)

![Image](https://github.com/bitcashorg/smartsale-evm/assets/391270/bcb1c360-46a4-42dd-a288-0377c0d03d51)

**Comment by gaboesquivel** [comment]
`info.edit.appName`

https://github.com/bitcashorg/smartsale/blob/develop/apps/webapp/lib/eos.ts#L90
https://github.com/bitcashorg/smartsale/blob/develop/apps/webapp/lib/eos.ts#L116

**Comment by AndlerRL** [comment]
Issue solved and working on production! Closing.
