### ISSUE TITLE
Add image lazy loader

### ISSUE THREAD

**Issue by AndlerRL** [bitcashorg/smartsale#37]
Similar from this [image loader](https://monosnap.com/file/3z4DV2e9XSoImOFAySklproGmixNbC):

- Each thumbnail and background image should have it.
  - Background images would not have the zoom out effect, only blur (avoiding dizziness).

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve UI/UX and Landing Hotfixes](https://trello.com/c/yYjjTXdk/25-improve-ui-ux-and-landing-hotfixes)

**Comment by gaboesquivel** [comment]
done
