### ISSUE TITLE
Confirmation on newsletter

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#40]
Add loading icon on button, show check on success. 

![Image](https://github.com/bitcashorg/smartsale-evm/assets/391270/14e0a4a1-46cf-4078-a20a-cad75e039ecf)

**Comment by AndlerRL** [comment]
Is not that is missing the success/error message (though the check is a nice improvement). I notice that is failling to submit the subscription:

![image](https://github.com/bitcashorg/smartsale/assets/35474730/c4ab7f6d-2152-41fa-8588-bb81128c3339)

This is the payload:

![image](https://github.com/bitcashorg/smartsale/assets/35474730/e61bf4f9-8f78-49bf-8117-9398cea460ad)

No console error what so ever on client side, so I went to vercel and I found:

![image](https://github.com/bitcashorg/smartsale/assets/35474730/166dc8e5-b67a-4aaf-b9c2-e298be4dbaa1)

And now noticing the site, the recaptcha icon is not showing on the site :thinking: are we missing something?

![image](https://github.com/bitcashorg/smartsale/assets/35474730/374f66ac-782b-4b53-8e6d-7947ee427efe)

![image](https://github.com/bitcashorg/smartsale/assets/35474730/e7eb7022-5b2b-4732-8f46-5e734f59e5e6)

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve UI/UX and Landing Hotfixes](https://trello.com/c/yYjjTXdk/25-improve-ui-ux-and-landing-hotfixes)

**Comment by AndlerRL** [comment]
Newsletter response feedback to users has been implemented! Error or success, it will display their appropriate icon on the CTA and a message below the input field. Closing
