### ISSUE TITLE
UI and copy adjustments

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#43]
Overall bitlauncher.ai looks good.  
Auction bidding page looks great. 

Issues:
1) seems to be overall lag on displaying content on scroll (both landing & project page)

2) Landing page UX:  Clicking arrow on landing page is not that intuitive to understand when it goes to Auction or Project Page. 
Let's just have the white circle icon with arrow point to Project Page.  Then the user will need another click to Auction by selecting 'Participate Now'.  Also we need to go to top of Project Page with Image & Auction Data and then have a 'Read More' at the bottom so they can get to read Highlights/Problem/Solution etc.

3) Small things.:
-bitcash | bitlauncher fundraising goal: $400k
-How It Works' .. capitalize 'W'
-You shouldn't have to click 'About' to have dropdown choices appear
-Increase size of 'Invest In The Intelligent Future' and add padding between Join the Ai/Web3 Revolution
-Max Allocation .. capitalize 'A'
-Remove © 2021 bitlauncher based in Silcon Valley at bottom
-Just label heading Tokenomics instead of "Tokenomics of Bitcash: Architectonic Value and Growth"

**Comment by AndlerRL** [comment]
After verifying, this issue is related to issue #39 #37.

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve UI/UX and Landing Hotfixes](https://trello.com/c/yYjjTXdk/25-improve-ui-ux-and-landing-hotfixes)
