### ISSUE TITLE
Webview ux and registration

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#48]
have an issue with this flow:

- I shared bitlauncer.ai on telegram
- people open it on their phones
- bitlauncher.ai open inside the telegram chat webview as all link
- you click on login or register
- app.bitcash.org opens inside  the telegram chat webview as all link
- on webview credentials will not be available, so they cannot login or register

This is super critical.   Maybe we can find a way to detect webviews thru browser user agent and show a message and button for people to copy the url on chorome or safari

![image](https://github.com/bitcashorg/smartsale/assets/391270/8c47b137-a137-4281-b0d8-68cef1c238f6)

**Comment by gaboesquivel** [comment]
If not possible to detect then we need a warning that shows up all the time.

**Comment by gaboesquivel** [comment]
If we encounter problems not with wa but metamask/rainbowkit/walletconnect on telegram webview, then we need a baner on webview:

Webviews are not supported. You must use Chrome, Safari or EVM wallet explorer like Metamask.
On the same Dialog for reading QR codes works

**Comment by AndlerRL** [comment]
The flow is correct. No issues with login from the WebView. We can drop the issues related to this and related with these mobile UX.

# DEMO

https://github.com/bitcashorg/smartsale/assets/35474730/f130e347-8b4f-45da-9a84-630cefad1c7d

**Comment by gaboesquivel** [comment]
Nice!
