### ISSUE TITLE
Test auction registration flow

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#49]
Test this flow on mobile and desktop

- share link on discord or telegram
- open link on mobile ( in messenger webview by default )
- login with bitcash
- login with metamask
- registrer metamaks address for bitcash auction

related to #48 
depends on #71

**Comment by AndlerRL** [comment]
@gaboesquivel -- We are good to go with this one. I will close it as completed due the results on issue #48
