### ISSUE TITLE
Optimize project card images on homepage

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#81]
To optimize the project card images on your homepage with a lazy load blur effect and ensure that Lighthouse reports pass, follow these steps:

1. **Implement Lazy Loading:**
   - Use the `loading="lazy"` attribute on your `<img>` tags to enable native lazy loading.
   - For browsers that don't support this, consider a JavaScript-based solution like `lazysizes`.

2. **Blur Image Effect:**
   - Create a low-resolution version of each main image. This should be very small (e.g., 20x20 pixels) and heavily compressed.
   - Initially display this blurred image as a placeholder. Use CSS `filter: blur(10px);` to enhance the blur effect if necessary.
   - Once the high-resolution image is loaded (via lazy loading), replace the blurred image with the full-resolution one.

3. **Optimize High-Resolution Images:**
   - Compress your images without significant loss of quality using tools like ImageOptim, TinyPNG, or similar.
   - Use the correct image format; consider WebP for better compression if browser compatibility allows.

4. **Responsive Images:**
   - Use `<picture>` elements or the `srcset` attribute on `<img>` elements to serve appropriately sized images based on the viewport size and device pixel ratio.

5. **Monitor and Adjust Based on Lighthouse Reports:**
   - Run Lighthouse audits to identify performance bottlenecks, including image-related issues.
   - Address any specific recommendations provided by Lighthouse to further optimize image handling.

By following these steps, you'll improve the performance and user experience of your homepage's images while ensuring good Lighthouse scores.

![Image](https://github.com/bitcashorg/smartsale/assets/391270/7843e87e-1195-4314-93cf-da7de87e22df)

![Image](https://github.com/bitcashorg/smartsale/assets/391270/ba4d0427-f525-47e5-9da6-569311b44dc1)

**Comment by gaboesquivel** [comment]
This needs more work [bitlauncher-lh.pdf](https://github.com/bitcashorg/smartsale/files/15322661/bitlauncher-lh.pdf)

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Development Support, Nathan - May 2024](https://trello.com/c/BWeEuUCM/28-development-support-nathan-may-2024)

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Development Support, Nathan - 2 of 2, May 2024](https://trello.com/c/LmiaK9br/39-development-support-nathan-2-of-2-may-2024)
