### ISSUE TITLE
Optimize newsletter bg image

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#83]
![image](https://github.com/bitcashorg/smartsale/assets/391270/85ef2b5a-3d4b-454a-8a0d-f205929c068f)

Same instructions as in #81

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Development Support, Nathan - May 2024](https://trello.com/c/BWeEuUCM/28-development-support-nathan-may-2024)
