### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/smartsale#85]
Same languages as bitcash app

Tasks: 

- translate with ai and translation tools
- setup language selector at the top

**Comment by AndlerRL** [comment]
Re-assigned to Jimoh. Localization has already started to develop by @sheriffjimoh .

Cc - @gaboesquivel @TopETH @merivercap

**Comment by gaboesquivel** [comment]
@sheriffjimoh dont work on project  landing page,  wait until my ui update from canary are merged

**Comment by gaboesquivel** [comment]
@sheriffjimoh please make your pr to the `blog` branch. it already has i18n setup on the middleware. 
Now you only need to add the dictionaries and update the components https://nextjs.org/docs/app/building-your-application/routing/internationalization#localization

**Comment by gaboesquivel** [comment]
![Image](https://github.com/bitcashorg/smartsale/assets/391270/27c64b7a-bb0a-4e9a-a11e-2be2f48873fc)
